export enum RootURLsEnum {
    registerChoose = '/choose',
    homepage = '/',
    regiserYacht = '/register/yacht',
    regiserSupplier = '/register/supplier',
    about = '/about',
    privacy = '/privacy',
    instructions = '/instructions',
    profile = '/profile',
    messages = '/messages',
    login = '/login',
    admin = '/admin',
    yacht = '/yacht',
    forgot = '/forgot',
    supplier = '/supplier',
    search = '/search',
    subscription = '/subscription'
}

export enum UserRoles {
    ADMIN = 'ADMIN',
    SUPPLIER = 'SUPPLIER',
    YACHT_BUSINESS = 'YACHT_BUSINESS',
    YACHT = 'YACHT',
    YACHT_TEAMMATE = 'YACHT_TEAMMATE'
}



export type UserRolesType = 'ADMIN' | 'SUPPLIER' | 'YACHT_BUSINESS' | 'YACHT' | 'YACHT_TEAMMATE'

export const YACHT_REGISTER_VARIANTS = ['Captain', 'Purser', 'Engineer', 'Chef', 'Interior', 'Deck']

export const mapProps = {
    mapStyle: 'mapbox://styles/mapbox/navigation-night-v1',
    mapboxAccessToken: process.env.NEXT_PUBLIC_MAPBOX_TOKEN
}

export const servicesList: Array<{ groupName: string, services: Array<string> }> = [
    {
        groupName: 'Captain & Purser',
        services: [
            'ACTIVITIES & THINGS TO DO',
'AIRCONDITIONING & VENTILATION',
'AMENITIES & SUPPLIES',
'AVIATION',
'AWNINGS, CANOPIES & COVERS',
'BATHROOM NECESSITIES',
'BEDROOM NECESSITIES',
'BUNKERING & FUEL',
'CARPENTERS & JOINERS',
'CARPET CLEANING',
'CARPETS & FLOORING',
'CHEFS NECESSITIES ',
'CHARTER MANAGEMENT & TIPS',
'CLUBS',
'COMPOSITE SERVICES',
'CONCIERGE',
'CREW AGENTS',
'CREW CERTIFICATION & REFRESHERS',
'CREW PROVISIONS',
'CUSTOMIZED FINISHES',
'CYCLING EQUIPMENT',
'DAVITS & HYDRAULICS',
'DECORATIVE ELEMENTS',
'DISCOVER NEW TECHNOLOGY',
'DIVING NECESSETIES & SERVICES',
'DOCK EQUIPMENT',
'DOORS & HATCHES',
'ELECTRICAL ENGINEERS',
'ENGINE SERVICES',
'ENGINEERING SUPPLIES',
'ENTERTAINMENT SYSTEMS',
'ENVIRONMENTAL COMPLIANCE',
'EVENTS COORDINATOR',
'FENDERS & FENDER COVERS',
'FIRE FIGHTING EQUIPMENT',
'FISHING EQUIPMENT',
'FLEET MANAGEMENT',
'FLORAL & PLANT SUPPLIERS',
'FLORISTS',
'FURNITURE',
'GALLEY EQUIPMENT',
'GALLEY EQUIPMENT & SERVICES',
'GENERATORS & POWER MANAGEMENT',
'GLASS SUPPLIERS & SERVICES',
'GYM & FITNESS GEAR',
'HAIRDRESSER CONSUMABLES',
'HAIRDRESSER EQUIPMENT & NECESSITIES',
'HELICOPTER REQUIREMENTS',
'IMMIGRATIONS & CUSTOMS',
'INSURANCE & FINANCIAL SERVICES',
'INTERNET & WIFI',
'INTERNET & WIFI',
'INVENTORY MANAGEMENT',
'LIFTS & ELEVATORS',
'LIGHTS & LIGHTING SPECIALISTS',
'LUXURY EVENTS & ENTERTAINMENTS',
'LUXURY ITEMS',
'LUXURY PET NECESSITIES',
'LUXURY TOILETRIES',
'MAINTENANCE & REPAIRS',
'MARINA EQUIPMENT',
'MARINE ELECTRONICS',
'MARITIME SAFETY',
'MEDICAL SUPPLIES & SERVICES',
'METAL WORKS & FABRICATIONS',
'MILE SUPPLIERS',
'MODEL MAKERS',
'NAVAL ARCHITECTS',
'NON-ALCOHOLIC BEVERAGES',
'ORGANISATIONAL ITEMS',
'PAINTING  & PAINT SPECIALISTS',
'PASSERELLES & BOARDING SYSTEMS',
'PHOTOGRAPHERS & VIDEOGRAPHERS',
'PORTS, MARINAS & BERTHS',
'PROPELLERS & PROPULSION',
'PROVISIONS',
'PROJECT MANAGEMENT & OWNERS REP',
'RADIOS & HEADSETS',
'REFRIGERATION EQUIPMENT & SERVICES',
'RESTAURANTS & BARS',
'SAILING & RIGGING',
'SAFETY GEAR',
'SATELLITE COMMUNICATION',
'SECURITY & SAFETY',
'SHIPPING & STORAGE',
'SHORESIDE ASSISTANCE',
'SHORESIDE CREW ACCOMMODATION',
'SHIPYARD FOR REFIT & REPAIR',
'SHIPYARDS FOR NEW BUILD',
'SPECIALITY CLEANING PRODUCTS',
'SPECIALIZED CLEANING',
'STABILIZER SERVICES',
'TABLEWARE',
'TENDERS & CHASE BOATS',
'TRAINING & COURSES',
'TRAVEL AGENTS',
'UNIFORM SUPPLIERS',
'UPHOLSTERY & FABRICS',
'UPHOLSTERY CLEANING',
'VILLAS & LUXURY HOTELS',
'VISA ASSISTANCE',
'WATER SPORTS EQUIPMENT',
'WATER TREATMENT',
'WINES & SPIRITS',
'YACHT ADMINISTRATION',
'YACHT AGENTS',
'YACHT CERTIFICATION',
'YACHT CHANDLERS',
'YACHT CHARTER & BROKER',
'YACHT DELIVERY & TRANSPORTATION',
'YACHT DESIGNER',
'YACHT MANAGEMENT',
'YACHT REGISTRATION & CLASSIFICATION',
'YACHT SIGNS'
        ]
    },
    {
        groupName: 'Engineering',
    services: [
        'AIRCONDITIONING & VENTILATION',
'AIRCONDITIONING & VENTILATION',
'AVIT REQUIREMENTS',
'AWNINGS, CANOPIES & COVERS',
'CARPETS & FLOORING',
'CREW ADMINISTRATION',
'CREW AGENTS',
'CREW CERTIFICATION & REFRESHERS',
'CREW WELFARE',
'DAVITS & HYDRAULICS',
'DISCOVER NEW TECHNOLOGY',
'DOORS & HATCHES',
'ELECTRICAL ENGINEERS',
'ENGINE SERVICES',
'ENGINEERING SUPPLIES',
'ENTERTAINMENT SYSTEMS',
'ENVIRONMENTAL COMPLIANCE',
'GALLEY EQUIPMENT & SERVICES',
'GENERATORS & POWER MANAGEMENT',
'GUEST ENTERTAINMENT',
'HELICOPTER REQUIREMENTS',
'INTERNET & WIFI',
'INTERNET & WIFI',
'INVENTORY MANAGEMENT',
'LAUNDRY EQUIPMENT & SERVICES',
'LIGHTS & LIGHTING SPECIALISTS',
'MAINTENANCE & REPAIRS',
'MARINE ELECTRONICS',
'METAL WORKS & FABRICATIONS',
'NAVIGATION, CHARTS & EQUIPMENT',
'ORGANISATIONAL ITEMS',
'PAINTING  & PAINT SPECIALISTS',
'PASSERELLES & BOARDING SYSTEMS',
'PHOTOGRAPHERS & VIDEOGRAPHERS',
'PROPELLERS & PROPULSION',
'RADIOS & HEADSETS',
'REFRIGERATION EQUIPMENT & SERVICES',
'SATELLITE COMMUNICATION',
'SHIPPING & STORAGE',
'SHORESIDE ASSISTANCE',
'SPECIALIZED CLEANING',
'STABILIZER SERVICES',
'TENDERS & CHASE BOATS',
'TRAINING & COURSES',
'VISA ASSISTANCE',
'WATER SPORTS EQUIPMENT',
'WATER TREATMENT',
'YACHT ADMINISTRATION',
'YACHT CHANDLERS',
'YACHT DELIVERY & TRANSPORTATION',
'YACHT SURVEYOR'
    ]
    },
    {
        groupName: 'Deck',
        services: [
            'BUNKERING & FUEL',
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'ENVIRONMENTAL COMPLIANCE',
            'INVENTORY MANAGEMENT',
            'MEDICAL SUPPLIES & SERVICES',
            'SECURITY & SAFETY',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'VISA ASSISTANCE',
            'YACHT ADMINISTRATION',
            'YACHT CERTIFICATION',
            'YACHT CHANDLERS',
            'YACHT SURVEYOR',
            'ACTIVITIES & THINGS TO DO',
            'CARPETS & FLOORING',
            'FURNITURE',
            'LUXURY PET NECESSITIES',
            'ORGANISATIONAL ITEMS',
            'SPECIALIZED CLEANING',
            'UPHOLSTERY CLEANING',
            'UPHOLSTERY CLEANING',
            'LIGHTS & LIGHTING SPECIALISTS',
            'MAINTENANCE & REPAIRS',
            'AVIATION',
            'AWNINGS, CANOPIES & COVERS',
            'CARPENTERS & JOINERS',
            'COMPOSITE SERVICES',
            'CYCLING EQUIPMENT',
            'DIVING NECESSETIES & SERVICES',
            'DOCK EQUIPMENT',
            'DOORS & HATCHES',
            'FENDERS & FENDER COVERS',
            'FIRE FIGHTING EQUIPMENT',
            'FISHING EQUIPMENT',
            'GLASS SUPPLIERS & SERVICES',
            'GYM & FITNESS GEAR',
            'HELICOPTER REQUIREMENTS',
            'INTERNET & WIFI',
            'MARINE ELECTRONICS',
            'METAL WORKS & FABRICATIONS',
            'NAVIGATION, CHARTS & EQUIPMENT',
            'PAINTING  & PAINT SPECIALISTS',
            'PASSERELLES & BOARDING SYSTEMS',
            'SAILING & RIGGING',
            'TENDERS & CHASE BOATS',
            'WATER SPORTS EQUIPMENT',
            'YACHT DELIVERY & TRANSPORTATION',
            'CREW WELFARE',
            'GUEST ENTERTAINMENT',
            'PHOTOGRAPHERS & VIDEOGRAPHERS',
        ]
    },
    {
        groupName: 'Interior',
        services: [
            'ACTIVITIES & THINGS TO DO',
            'BATHROOM NECESSITIES',
            'BEDROOM NECESSITIES',
            'CARPET CLEANING',
            'CARPETS & FLOORING',
            'CHAUFFEURS & CAR HIRE',
            'CLUBS',
            'CONCIERGE',
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'CREW PROVISIONS',
            'CREW WELFARE',
            'DECORATIVE ELEMENTS',
            'EVENTS COORDINATOR',
            'FLORAL & PLANT SUPPLIERS',
            'FLORISTS',
            'FURNITURE',
            'GALLEY EQUIPMENT',
            'GYM & FITNESS GEAR',
            'HAIRDRESSER CONSUMABLES',
            'HAIRDRESSER EQUIPMENT & NECESSITIES',
            'INVENTORY MANAGEMENT',
            'LIGHTS & LIGHTING SPECIALISTS',
            'LUXURY EVENTS & ENTERTAINMENTS',
            'LUXURY ITEMS',
            'LUXURY PET NECESSITIES',
            'LUXURY TOILETRIES',
            'LAUNDRY EQUIPMENT & SERVICES',
            'NON-ALCOHOLIC BEVERAGES',
            'ORGANISATIONAL ITEMS',
            'PHOTOGRAPHERS & VIDEOGRAPHERS',
            'PROVISIONS',
            'RESTAURANTS & BARS',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'SHORESIDE CREW ACCOMMODATION',
            'SPECIALITY CLEANING PRODUCTS',
            'SPECIALIZED CLEANING',
            'SPA CONSUMABLES',
            'SPA EQUIPMENT & NECESSITIES',
            'SPAS',
            'TABLEWARE',
            'TRAINING & COURSES',
            'TRAVEL AGENTS',
            'UNIFORM SUPPLIERS',
            'UPHOLSTERY & FABRICS',
            'UPHOLSTERY CLEANING',
            'VILLA & LUXURY HOTELS',
            'VISA ASSISTANCE',
            'WINES & SPIRITS',
            'YACHT ADMINISTRATION',
            'YACHT CHANDLERS',
            'CREW ADMINISTRATION',
            'GUEST ENTERTAINMENT',
        ]        
    },
    {
        groupName: 'Galley',
        services: [
            "CHEF'S NECESSITIES",
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'CREW PROVISIONS',
            'GALLEY EQUIPMENT',
            'INVENTORY MANAGEMENT',
            'NON-ALCOHOLIC BEVERAGES',
            'ORGANISATIONAL ITEMS',
            'PROVISIONS',
            'REFRIGERATION EQUIPMENT & SERVICES',
            'RESTAURANTS & BARS',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'VISA ASSISTANCE',
            'WINES & SPIRITS',
            'WINES & SPIRITS',
            'YACHT ADMINISTRATION',
            'YACHT CHANDLERS',
        ]        
    },
    {
        groupName: 'Security',
        services: [
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'INVENTORY MANAGEMENT',
            'MARITIME SAFETY',
            'SECURITY & SAFETY',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'VISA ASSISTANCE',
            'YACHT ADMINISTRATION',
            'YACHT CHANDLERS',
        ]        
    }
]

export const loactionList: Array<{ groupName: string, countries: Array<string> }> = [
    {
        groupName: 'Europe',
        countries: [
            'Albania',
            'Andorra',
            'Austria',
            'Belarus',
            'Belgium',
            'Bosnia and Herzegovina',
            'Bulgaria',
            'Croatia',
            'Cyprus',
            'Czech Republic',
            'Denmark',
            'Estonia',
            'Finland',
            'Germany',
            'Greece',
            'Hungary',
            'Iceland',
            'Ireland',
            'Italy',
            'Latvia',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Malta',
            'Monaco',
            'Montenegro',
            'Macedonia',
            'Netherlands',
            'Norway',
            'Poland',
            'Portugal',
            'Romania',
            'Russia',
            'San Marino',
            'Serbia',
            'Slovakia',
            'Slovenia',
            'Spain',
            'Sweden',
            'Switzerland',
            'Ukraine',
            'United Kingdom',
            'Åland Islands',
            'Azores',
            'Canary Islands',
            'Faroe Islands',
            'Gibraltar',
            'Guernsey',
            'Isle of Man',
            'Jan Mayen',
            'Jersey',
            'Madeira',
            'Svalbard',
            'Palma',
            'Ibiza',
            'Corsica',
            'Sardinia',
            'Sicily',
            'Malta',
            'Crete',
            'Cyprus',
            'Santorini',
            'Mykonos',
            'Rhodes',
            'Corfu',
            'Capri',
        ]
    },
    {
        groupName: 'Aisia',
        countries: [
            'Armenia',
            'Bahrain',
            'Bangladesh',
            'Brunei',
            'Cambodia',
            'China',
            'Cyprus',
            'Georgia',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Israel',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kuwait',
            'Kyrgyzstan',
            'Lebanon',
            'Malaysia',
            'Maldives',
            'North Korea',
            'Oman',
            'Palestine',
            'Philippines',
            'Qatar',
            'Saudi Arabia',
            'Singapore',
            'South Korea',
            'Sri Lanka',
            'Syria',
            'Taiwan',
            'Thailand',
            'Timor - Leste',
            'Turkey',
            'United Arab Emirates',
            'Vietnam',
            'Andaman Islands',
            'Nicobar Islands',
            'Hainan Island',
            'Sumatra',
            'Java',
            'Borneo',
            'Sulawesi',
            'Bali',
            'Luzon',
            'Mindanao',
            'Hokkaido',
            'Honshu',
            'Kyushu',
            'Shikoku',
            'Sri Lanka',
            'Taiwan',
            'Haida Gwaii',
            'Sakhalin',
            'Kuril Islands',
            'Jeju Island',
            'Phuket',
            'Maldives',
            'Socotra',
            'Seychelles',
            'Sriwijaya',
            'Penghu Islands',
            'Okinawa Islands',
        ]
    },
    {
        groupName: 'North America',
        countries: [
            'Canada',
            'United States',
            'Mexico',
            'Antigua and Barbuda',
            'Bahamas',
            'Barbados',
            'Belize',
            'Cuba',
            'Dominica',
            'Dominican Republic',
            'Grenada',
            'Haiti',
            'Jamaica',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Vincent and the Grenadines',
            'Trinidad and Tobago',
            'Anguilla',
            'Aruba',
            'Bermuda',
            'Bonaire',
            'British Virgin Islands',
            'Cayman Islands',
            'Curaçao',
            'Greenland',
            'Guadeloupe',
            'Martinique',
            'Montserrat',
            'Navassa Island',
            'Puerto Rico',
            'Saint Martin',
            'Sint Maarten',
            'Turks and Caicos Islands',
            'U.S. Virgin Islands',
            'Vancouver Island',
            'Vancouver',
            'Newfoundland and Labrador',
            'Hispaniola (shared by Haiti and the Dominican Republic)',
            'Cuba',
            'Jamaica',
            'Cozumel',
            'Isla Mujeres',
            'Isla Holbox',
            'Isla Contoy',
            'Isla Mujeres',
            'Isla Holbox',
            'Isla Contoy',
        ]
    },
    {
        groupName: 'South America',
        countries: [
            'Argentina',
            'Bolivia',
            'Brazil',
            'Chile',
            'Costa Rica',
            'Colombia',
            'Ecuador',
            'Guyana',
            'Honduras',
            'Nicaragua',
            'Paraguay',
            'Panama',
            'Peru',
            'Suriname',
            'El Salvdor',
            'Uruguay',
            'Venezuela',
            'French Guiana',
            'Falkland Islands',
            'South Georgia and the South Sandwich Islands',
            'Galápagos Islands',
            'Juan Fernández Islands',
            'Chiloé Archipelago',
            'Tierra del Fuego',
            'Ilhabela',
            'Fernando de Noronha',
            'Ilha Grande',
            'Ilha de Marajó',
            'Margarita Island',
            'Ilha do Mel',
            'Easter Island',
        ]
    },
    {
        groupName: 'Africa',
        countries: [
            'Algeria',
            'Angola',
            'Botswana',
            'Cabo Verde',
            'Cameroon',
            'Congo',
            'Egypt',
            'Equatorial Guinea',
            'Gabon',
            'Ghana',
            "Ivory Coast (Côte d'Ivoire)",
            'Kenya',
            'Libya',
            'Madagascar',
            'Malawi',
            'Mauritius',
            'Morocco',
            'Mozambique',
            'Namibia',
            'Nigeria',
            'Senegal',
            'Seychelles',
            'Sierra Leone',
            'Somalia',
            'South Africa',
            'Tanzania',
            'Tunisia',
            'Canary Islands',
            'Ceuta and Melilla',
            'Madeira',
            'Mayotte',
            'Saint Helena, Ascension, and Tristan da Cunha',
            'Cape Verde Islands',
            'Zanzibar',
            'Socotra',
            'Madagascar',
            'Seychelles Islands',
            'Comoros Islands',
            'Canary Islands',
            'Madeira',
            'São Tomé and Príncipe Islands',
            'Mauritius',
            'Reunion Island',
            'Ascension Island',
            'Tristan da Cunha',
            'Solomon Island',
        ]
    },
    {
        groupName: 'Antarctica',
        countries: [
            'Antarctica',
            'King George Island',
            'Deception Island',
            'Livingston Island',
            'Macquarie Island',
            'Heard Island and McDonald Islands'
        ]
    },
    {
        groupName: 'Australia',
        countries: [
            'Australia',
            'New Zealand',
            'Ashmore and Cartier Islands',
            'Australian Antarctic Territory',
            'Christmas Island',
            'Cocos (Keeling) Islands',
            'Coral Sea Islands',
            'Heard Island and McDonald Islands',
            'Norfolk Island',
            'French Polynesia',
            'Marshall Islands',
            'Niue',
            'Samoa',
            'New Caledonia',
            'Fiji',
            'Tasmania',
            'Kangaroo Island',
            'Fraser Island',
            'Groote Eylandt',
            'Rottnest Island',
            'Lord Howe Island',
            'Norfolk Island',
            'Tiwi Islands',
            'Whitsunday Islands',
            'Magnetic Island',
            'Phillip Island',
            'Hamilton Island',
            'Hayman Island',
            'Flinders Island',
            'Thursday Island',
            'South Stradbroke Island',
            'Moreton Island',
            'Papua New Guinea',
        ]
    }
]