export enum RootURLsEnum {
    registerChoose = '/choose',
    homepage = '/',
    regiserYacht = '/register/yacht',
    regiserSupplier = '/register/supplier',
    about = '/about',
    privacy = '/privacy',
    instructions = '/instructions',
    profile = '/profile',
    messages = '/messages',
    login = '/login',
    admin = '/admin',
    yacht = '/yacht',
    forgot = '/forgot',
    supplier = '/supplier',
    search = '/search',
    subscription = '/subscription'
}

export enum UserRoles {
    ADMIN = 'ADMIN',
    SUPPLIER = 'SUPPLIER',
    YACHT_BUSINESS = 'YACHT_BUSINESS',
    YACHT = 'YACHT',
    YACHT_TEAMMATE = 'YACHT_TEAMMATE'
}



export type UserRolesType = 'ADMIN' | 'SUPPLIER' | 'YACHT_BUSINESS' | 'YACHT' | 'YACHT_TEAMMATE'

export const YACHT_REGISTER_VARIANTS = ['Captain', 'Purser', 'Engineer', 'Chef', 'Interior', 'Deck']

export const mapProps = {
    mapStyle: 'mapbox://styles/mapbox/navigation-night-v1',
    mapboxAccessToken: process.env.NEXT_PUBLIC_MAPBOX_TOKEN
}

export const servicesList: Array<{ groupName: string, services: Array<string> }> = [
    {
        groupName: 'Captain & Purser',
        services: [
            'BUNKERING & FUEL',
            'CHARTER MANAGEMENT & TIPS',
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'ENVIRONMENTAL COMPLIANCE',
            'FLEET MANAGEMENT',
            'IMMIGRATIONS & CUSTOMS',
            'INSURANCE & FINANCIAL SERVICES',
            'INVENTORY MANAGEMENT',
            'LEGAL SERVICES',
            'MARITIME SAFETY',
            'MEDICAL SUPPLIES & SERVICES',
            'PORTS, MARINAS & BERTHS',
            'PROJECT MANAGEMENT & OWNERS REP',
            'SECURITY & SAFETY',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'TRAVEL AGENTS',
            'VISA ASSISTANCE',
            'YACHT ADMINISTRATION',
            'YACHT AGENTS',
            'YACHT CERTIFICATION',
            'YACHT CHANDLERS',
            'YACHT CHARTER & BROKER',
            'YACHT MANAGEMENT',
            'YACHT SURVEYOR',
            'ACTIVITIES & THINGS TO DO',
            'CHAUFFEURS & CAR HIRE',
            'CLUBS',
            'CONCIERGE',
            'EVENTS COORDINATOR',
            'LUXURY EVENTS & ENTERTAINMENTS',
            'RESTAURANTS & BARS',
            'SHORESIDE CREW ACCOMMODATION',
            'SPAS',
            'VILLAS & LUXURY HOTELS',
            'BATHROOM NECESSITIES',
            'BEDROOM NECESSITIES',
            'CARPET CLEANING',
            'CARPETS & FLOORING',
            "CHEF'S NECESSITIES ",
            'CREW PROVISIONS',
            'DECORATIVE ELEMENTS',
            'FLORAL & PLANT SUPPLIERS',
            'FLORISTS',
            'FURNITURE',
            'GALLEY EQUIPMENT',
            'HAIRDRESSER CONSUMABLES',
            'HAIRDRESSER EQUIPMENT & NECESSITIES',
            'LUXURY ITEMS',
            'LUXURY PET NECESSITIES',
            'LUXURY TOILETRIES',
            'NON-ALCOHOLIC BEVERAGES',
            'ORGANISATIONAL ITEMS',
            'PROVISIONS',
            'SPA CONSUMABLES',
            'SPA EQUIPMENT & NECESSITIES',
            'SPECIALITY CLEANING PRODUCTS',
            'SPECIALIZED CLEANING',
            'TABLEWARE',
            'UNIFORM SUPPLIERS',
            'UPHOLSTERY & FABRICS',
            'UPHOLSTERY CLEANING',
            'WINES & SPIRITS',
            'AIRCONDITIONING & VENTILATION',
            'AVIT REQUIREMENTS',
            'DAVITS & HYDRAULICS',
            'DISCOVER NEW TECHNOLOGY',
            'ELECTRICAL ENGINEERS',
            'ENGINE SERVICES',
            'ENGINEERING SUPPLIES',
            'ENTERTAINMENT SYSTEMS',
            'GALLEY EQUIPMENT & SERVICES',
            'GENERATORS & POWER MANAGEMENT',
            'INTERNET & WIFI',
            'LAUNDRY EQUIPMENT & SERVICES',
            'LIFTS & ELEVATORS',
            'LIGHTS & LIGHTING SPECIALISTS',
            'MAINTENANCE & REPAIRS',
            'PROPELLERS & PROPULSION',
            'RADIOS & HEADSETS',
            'REFRIGERATION EQUIPMENT & SERVICES',
            'SATELLITE COMMUNICATION',
            'STABILIZER SERVICES',
            'WATER TREATMENT',
            'CUSTOMIZED FINISHES',
            'INTERIOR DESIGNERS',
            'MARINA EQUIPMENT',
            'MODEL MAKERS',
            'NAVAL ARCHITECTS',
            'SAFETY GEAR',
            'SHIPYARD FOR REFIT & REPAIR',
            'SHIPYARDS FOR NEW BUILD',
            'SPECIALIZED REPAIRS',
            'YACHT DESIGNER',
            'YACHT REGISTRATION & CLASSIFICATION',
            'YACHT SIGNS',
            'AVIATION',
            'AWNINGS, CANOPIES & COVERS',
            'CARPENTERS & JOINERS',
            'COMPOSITE SERVICES',
            'CYCLING EQUIPMENT',
            'DIVING NECESSETIES & SERVICES',
            'DOCK EQUIPMENT',
            'DOORS & HATCHES',
            'FENDERS & FENDER COVERS',
            'FIRE FIGHTING EQUIPMENT',
            'FISHING EQUIPMENT',
            'GLASS SUPPLIERS & SERVICES',
            'GYM & FITNESS GEAR',
            'HELICOPTER REQUIREMENTS',
            'INTERNET & WIFI',
            'MARINE ELECTRONICS',
            'METAL WORKS & FABRICATIONS',
            'NAVIGATION, CHARTS & EQUIPMENT',
            'PAINTING  & PAINT SPECIALISTS',
            'PASSERELLES & BOARDING SYSTEMS',
            'SAILING & RIGGING',
            'TENDERS & CHASE BOATS',
            'WATER SPORTS EQUIPMENT',
            'YACHT DELIVERY & TRANSPORTATION',
            'CREW WELFARE',
            'GUEST ENTERTAINMENT',
            'PHOTOGRAPHERS & VIDEOGRAPHERS',
            'MILE SUPPLIERS',
        ]
    },
    {
        groupName: 'Engineering',
        services: [
            'BUNKERING & FUEL',
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'ENVIRONMENTAL COMPLIANCE',
            'INVENTORY MANAGEMENT',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'VISA ASSISTANCE',
            'YACHT ADMINISTRATION',
            'YACHT CHANDLERS',
            'YACHT SURVEYOR',
            'CARPETS & FLOORING',
            'FURNITURE',
            'ORGANISATIONAL ITEMS',
            'SPECIALIZED CLEANING',
            'AIRCONDITIONING & VENTILATION',
            'AVIT REQUIREMENTS',
            'DAVITS & HYDRAULICS',
            'DISCOVER NEW TECHNOLOGY',
            'ELECTRICAL ENGINEERS',
            'ENGINE SERVICES',
            'ENGINEERING SUPPLIES',
            'ENTERTAINMENT SYSTEMS',
            'GALLEY EQUIPMENT & SERVICES',
            'GENERATORS & POWER MANAGEMENT',
            'INTERNET & WIFI',
            'LAUNDRY EQUIPMENT & SERVICES',
            'LIFTS & ELEVATORS',
            'LIGHTS & LIGHTING SPECIALISTS',
            'MAINTENANCE & REPAIRS',
            'PROPELLERS & PROPULSION',
            'RADIOS & HEADSETS',
            'REFRIGERATION EQUIPMENT & SERVICES',
            'SATELLITE COMMUNICATION',
            'STABILIZER SERVICES',
            'WATER TREATMENT',
            'AWNINGS, CANOPIES & COVERS',
            'DOORS & HATCHES',
            'HELICOPTER REQUIREMENTS',
            'INTERNET & WIFI',
            'MARINE ELECTRONICS',
            'METAL WORKS & FABRICATIONS',
            'NAVIGATION, CHARTS & EQUIPMENT',
            'PAINTING  & PAINT SPECIALISTS',
            'PASSERELLES & BOARDING SYSTEMS',
            'SAILING & RIGGING',
            'TENDERS & CHASE BOATS',
            'WATER SPORTS EQUIPMENT',
            'YACHT DELIVERY & TRANSPORTATION',
            'CREW WELFARE',
            'GUEST ENTERTAINMENT',
            'PHOTOGRAPHERS & VIDEOGRAPHERS',
        ]
    },
    {
        groupName: 'Deck',
        services: [
            'BUNKERING & FUEL',
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'ENVIRONMENTAL COMPLIANCE',
            'INVENTORY MANAGEMENT',
            'MEDICAL SUPPLIES & SERVICES',
            'SECURITY & SAFETY',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'VISA ASSISTANCE',
            'YACHT ADMINISTRATION',
            'YACHT CERTIFICATION',
            'YACHT CHANDLERS',
            'YACHT SURVEYOR',
            'ACTIVITIES & THINGS TO DO',
            'CARPETS & FLOORING',
            'FURNITURE',
            'LUXURY PET NECESSITIES',
            'ORGANISATIONAL ITEMS',
            'SPECIALIZED CLEANING',
            'UPHOLSTERY CLEANING',
            'UPHOLSTERY CLEANING',
            'LIGHTS & LIGHTING SPECIALISTS',
            'MAINTENANCE & REPAIRS',
            'AVIATION',
            'AWNINGS, CANOPIES & COVERS',
            'CARPENTERS & JOINERS',
            'COMPOSITE SERVICES',
            'CYCLING EQUIPMENT',
            'DIVING NECESSETIES & SERVICES',
            'DOCK EQUIPMENT',
            'DOORS & HATCHES',
            'FENDERS & FENDER COVERS',
            'FIRE FIGHTING EQUIPMENT',
            'FISHING EQUIPMENT',
            'GLASS SUPPLIERS & SERVICES',
            'GYM & FITNESS GEAR',
            'HELICOPTER REQUIREMENTS',
            'INTERNET & WIFI',
            'MARINE ELECTRONICS',
            'METAL WORKS & FABRICATIONS',
            'NAVIGATION, CHARTS & EQUIPMENT',
            'PAINTING  & PAINT SPECIALISTS',
            'PASSERELLES & BOARDING SYSTEMS',
            'SAILING & RIGGING',
            'TENDERS & CHASE BOATS',
            'WATER SPORTS EQUIPMENT',
            'YACHT DELIVERY & TRANSPORTATION',
            'CREW WELFARE',
            'GUEST ENTERTAINMENT',
            'PHOTOGRAPHERS & VIDEOGRAPHERS',
        ]
    },
    {
        groupName: 'Interior',
        services: [
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'INVENTORY MANAGEMENT',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'TRAVEL AGENTS',
            'VISA ASSISTANCE',
            'YACHT ADMINISTRATION',
            'YACHT CHANDLERS',
            'ACTIVITIES & THINGS TO DO',
            'CHAUFFEURS & CAR HIRE',
            'CLUBS',
            'CONCIERGE',
            'EVENTS COORDINATOR',
            'LUXURY EVENTS & ENTERTAINMENTS',
            'RESTAURANTS & BARS',
            'SHORESIDE CREW ACCOMMODATION',
            'SPAS',
            'VILLAS & LUXURY HOTELS',
            'BATHROOM NECESSITIES',
            'BEDROOM NECESSITIES',
            'CARPET CLEANING',
            'CARPETS & FLOORING',
            'CREW PROVISIONS',
            'DECORATIVE ELEMENTS',
            'FLORAL & PLANT SUPPLIERS',
            'FLORISTS',
            'FURNITURE',
            'GALLEY EQUIPMENT',
            'HAIRDRESSER CONSUMABLES',
            'HAIRDRESSER EQUIPMENT & NECESSITIES',
            'LUXURY ITEMS',
            'LUXURY PET NECESSITIES',
            'LUXURY TOILETRIES',
            'NON-ALCOHOLIC BEVERAGES',
            'ORGANISATIONAL ITEMS',
            'PROVISIONS',
            'SPA CONSUMABLES',
            'SPA EQUIPMENT & NECESSITIES',
            'SPECIALITY CLEANING PRODUCTS',
            'SPECIALIZED CLEANING',
            'TABLEWARE',
            'UNIFORM SUPPLIERS',
            'UPHOLSTERY & FABRICS',
            'UPHOLSTERY CLEANING',
            'WINES & SPIRITS',
            'LAUNDRY EQUIPMENT & SERVICES',
            'LIGHTS & LIGHTING SPECIALISTS',
            'GYM & FITNESS GEAR',
            'CREW WELFARE',
            'GUEST ENTERTAINMENT',
            'PHOTOGRAPHERS & VIDEOGRAPHERS',
        ]
    },
    {
        groupName: 'Galley',
        services: [
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'INVENTORY MANAGEMENT',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'VISA ASSISTANCE',
            'YACHT ADMINISTRATION',
            'YACHT CHANDLERS',
            'RESTAURANTS & BARS',
            "CHEF'S NECESSITIES",
            'CREW PROVISIONS',
            'GALLEY EQUIPMENT',
            'NON-ALCOHOLIC BEVERAGES',
            'ORGANISATIONAL ITEMS',
            'PROVISIONS',
            'WINES & SPIRITS',
            'WINES & SPIRITS',
            'REFRIGERATION EQUIPMENT & SERVICES',
        ]
    },
    {
        groupName: 'Security',
        services: [
            'CREW AGENTS',
            'CREW CERTIFICATION & REFRESHERS',
            'INVENTORY MANAGEMENT',
            'MARITIME SAFETY',
            'SECURITY & SAFETY',
            'SHIPPING & STORAGE',
            'SHORESIDE ASSISTANCE',
            'TRAINING & COURSES',
            'VISA ASSISTANCE',
            'YACHT ADMINISTRATION',
            'YACHT CHANDLERS',
        ]
    }
]

export const loactionList: Array<{ groupName: string, countries: Array<string> }> = [
    {
        groupName: 'Europe',
        countries: [
            'Albania',
            'Andorra',
            'Austria',
            'Belarus',
            'Belgium',
            'Bosnia and Herzegovina',
            'Bulgaria',
            'Croatia',
            'Cyprus',
            'Czech Republic',
            'Denmark',
            'Estonia',
            'Finland',
            'Germany',
            'Greece',
            'Hungary',
            'Iceland',
            'Ireland',
            'Italy',
            'Latvia',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Malta',
            'Monaco',
            'Montenegro',
            'Macedonia',
            'Netherlands',
            'Norway',
            'Poland',
            'Portugal',
            'Romania',
            'Russia',
            'San Marino',
            'Serbia',
            'Slovakia',
            'Slovenia',
            'Spain',
            'Sweden',
            'Switzerland',
            'Ukraine',
            'United Kingdom',
            'Åland Islands',
            'Azores',
            'Canary Islands',
            'Faroe Islands',
            'Gibraltar',
            'Guernsey',
            'Isle of Man',
            'Jan Mayen',
            'Jersey',
            'Madeira',
            'Svalbard',
            'Palma',
            'Ibiza',
            'Corsica',
            'Sardinia',
            'Sicily',
            'Malta',
            'Crete',
            'Cyprus',
            'Santorini',
            'Mykonos',
            'Rhodes',
            'Corfu',
            'Capri',
        ]
    },
    {
        groupName: 'Aisia',
        countries: [
            'Armenia',
            'Bahrain',
            'Bangladesh',
            'Brunei',
            'Cambodia',
            'China',
            'Cyprus',
            'Georgia',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Israel',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kuwait',
            'Kyrgyzstan',
            'Lebanon',
            'Malaysia',
            'Maldives',
            'North Korea',
            'Oman',
            'Palestine',
            'Philippines',
            'Qatar',
            'Saudi Arabia',
            'Singapore',
            'South Korea',
            'Sri Lanka',
            'Syria',
            'Taiwan',
            'Thailand',
            'Timor - Leste',
            'Turkey',
            'United Arab Emirates',
            'Vietnam',
            'Andaman Islands',
            'Nicobar Islands',
            'Hainan Island',
            'Sumatra',
            'Java',
            'Borneo',
            'Sulawesi',
            'Bali',
            'Luzon',
            'Mindanao',
            'Hokkaido',
            'Honshu',
            'Kyushu',
            'Shikoku',
            'Sri Lanka',
            'Taiwan',
            'Haida Gwaii',
            'Sakhalin',
            'Kuril Islands',
            'Jeju Island',
            'Phuket',
            'Maldives',
            'Socotra',
            'Seychelles',
            'Sriwijaya',
            'Penghu Islands',
            'Okinawa Islands',
        ]
    },
    {
        groupName: 'North America',
        countries: [
            'Canada',
            'United States',
            'Mexico',
            'Antigua and Barbuda',
            'Bahamas',
            'Barbados',
            'Belize',
            'Cuba',
            'Dominica',
            'Dominican Republic',
            'Grenada',
            'Haiti',
            'Jamaica',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Vincent and the Grenadines',
            'Trinidad and Tobago',
            'Anguilla',
            'Aruba',
            'Bermuda',
            'Bonaire',
            'British Virgin Islands',
            'Cayman Islands',
            'Curaçao',
            'Greenland',
            'Guadeloupe',
            'Martinique',
            'Montserrat',
            'Navassa Island',
            'Puerto Rico',
            'Saint Martin',
            'Sint Maarten',
            'Turks and Caicos Islands',
            'U.S. Virgin Islands',
            'Vancouver Island',
            'Vancouver',
            'Newfoundland and Labrador',
            'Hispaniola (shared by Haiti and the Dominican Republic)',
            'Cuba',
            'Jamaica',
            'Cozumel',
            'Isla Mujeres',
            'Isla Holbox',
            'Isla Contoy',
            'Isla Mujeres',
            'Isla Holbox',
            'Isla Contoy',
        ]
    },
    {
        groupName: 'South America',
        countries: [
            'Argentina',
            'Bolivia',
            'Brazil',
            'Chile',
            'Costa Rica',
            'Colombia',
            'Ecuador',
            'Guyana',
            'Honduras',
            'Nicaragua',
            'Paraguay',
            'Panama',
            'Peru',
            'Suriname',
            'El Salvdor',
            'Uruguay',
            'Venezuela',
            'French Guiana',
            'Falkland Islands',
            'South Georgia and the South Sandwich Islands',
            'Galápagos Islands',
            'Juan Fernández Islands',
            'Chiloé Archipelago',
            'Tierra del Fuego',
            'Ilhabela',
            'Fernando de Noronha',
            'Ilha Grande',
            'Ilha de Marajó',
            'Margarita Island',
            'Ilha do Mel',
            'Easter Island',
        ]
    },
    {
        groupName: 'Africa',
        countries: [
            'Algeria',
            'Angola',
            'Botswana',
            'Cabo Verde',
            'Cameroon',
            'Congo',
            'Egypt',
            'Equatorial Guinea',
            'Gabon',
            'Ghana',
            "Ivory Coast (Côte d'Ivoire)",
            'Kenya',
            'Libya',
            'Madagascar',
            'Malawi',
            'Mauritius',
            'Morocco',
            'Mozambique',
            'Namibia',
            'Nigeria',
            'Senegal',
            'Seychelles',
            'Sierra Leone',
            'Somalia',
            'South Africa',
            'Tanzania',
            'Tunisia',
            'Canary Islands',
            'Ceuta and Melilla',
            'Madeira',
            'Mayotte',
            'Saint Helena, Ascension, and Tristan da Cunha',
            'Cape Verde Islands',
            'Zanzibar',
            'Socotra',
            'Madagascar',
            'Seychelles Islands',
            'Comoros Islands',
            'Canary Islands',
            'Madeira',
            'São Tomé and Príncipe Islands',
            'Mauritius',
            'Reunion Island',
            'Ascension Island',
            'Tristan da Cunha',
            'Solomon Island',
        ]
    },
    {
        groupName: 'Antarctica',
        countries: [
            'Antarctica',
            'King George Island',
            'Deception Island',
            'Livingston Island',
            'Macquarie Island',
            'Heard Island and McDonald Islands'
        ]
    },
    {
        groupName: 'Australia',
        countries: [
            'Australia',
            'New Zealand',
            'Ashmore and Cartier Islands',
            'Australian Antarctic Territory',
            'Christmas Island',
            'Cocos (Keeling) Islands',
            'Coral Sea Islands',
            'Heard Island and McDonald Islands',
            'Norfolk Island',
            'French Polynesia',
            'Marshall Islands',
            'Niue',
            'Samoa',
            'New Caledonia',
            'Fiji',
            'Tasmania',
            'Kangaroo Island',
            'Fraser Island',
            'Groote Eylandt',
            'Rottnest Island',
            'Lord Howe Island',
            'Norfolk Island',
            'Tiwi Islands',
            'Whitsunday Islands',
            'Magnetic Island',
            'Phillip Island',
            'Hamilton Island',
            'Hayman Island',
            'Flinders Island',
            'Thursday Island',
            'South Stradbroke Island',
            'Moreton Island',
            'Papua New Guinea',
        ]
    }
]