export enum RootURLsEnum {
    registerChoose = '/choose',
    homepage = '/',
    regiserYacht = '/register/yacht',
    regiserSupplier = '/register/supplier',
    about = '/about',
    privacy = '/privacy',
    instructions = '/instructions',
    profile = '/profile',
    messages = '/messages',
    login = '/login',
    admin = '/admin',
    yacht = '/yacht',
    forgot = '/forgot',
    supplier = '/supplier',
    search = '/search',
    subscription = '/subscription'
}

export enum UserRoles {
    ADMIN = 'ADMIN',
    SUPPLIER = 'SUPPLIER',
    YACHT_BUSINESS = 'YACHT_BUSINESS',
    YACHT = 'YACHT',
    YACHT_TEAMMATE = 'YACHT_TEAMMATE'
}



export type UserRolesType = 'ADMIN' | 'SUPPLIER' | 'YACHT_BUSINESS' | 'YACHT' | 'YACHT_TEAMMATE'

export const YACHT_REGISTER_VARIANTS = ['Captain', 'Purser', 'Engineer', 'Chef', 'Interior', 'Deck']

export const mapProps = {
    mapStyle: 'mapbox://styles/mapbox/navigation-night-v1',
    mapboxAccessToken: process.env.NEXT_PUBLIC_MAPBOX_TOKEN
}

export const departmentsList: Array<string> = [
    'Captain',
    'Purser',
    'Engineering',
    'AVIT and ETO',
    'Deck',
    'PT and Fitness',
    'Diving',
    'Security',
    'Galley',
    'Interior',
    'Service',
    'Housekeeping',
    'Spa',
    'Safety',
    'New Build',
    'Charter',
]

export const servicesList: Array<string> = [
    'YACHT CERTIFICATION',
    'INSURANCE & FINANCIAL SERVICES',
    'OWNERS REP & PROJECT MANAGEMENT',
    'LEGAL SERVICES',
    'CHARTER & TIP MANAGEMENT',
    'CHARTER BROKERS',
    'TRAINING & COURSES',
    'NAVAL ARCHITECTS',
    'YACHT DESIGNERS',
    'INTERIOR DESIGNERS',
    'MODEL MAKERS',
    'CREW ACCOMODATION',
    'SAFETY GEAR',
    'LOCAL ENTERTAINMENT',
    'PROVISIONS',
    'BEVERAGES',
]

export const loactionList: Array<{ groupName: string, countries: Array<string> }> = [
    {
        groupName: 'Europe',
        countries: [
            'Albania',
            'Andorra',
            'Austria',
            'Belarus',
            'Belgium',
            'Bosnia and Herzegovina',
            'Bulgaria',
            'Croatia',
            'Cyprus',
            'Czech Republic',
            'Denmark',
            'Estonia',
            'Finland',
            'Germany',
            'Greece',
            'Hungary',
            'Iceland',
            'Ireland',
            'Italy',
            'Latvia',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Malta',
            'Monaco',
            'Montenegro',
            'Macedonia',
            'Netherlands',
            'Norway',
            'Poland',
            'Portugal',
            'Romania',
            'Russia',
            'San Marino',
            'Serbia',
            'Slovakia',
            'Slovenia',
            'Spain',
            'Sweden',
            'Switzerland',
            'Ukraine',
            'United Kingdom',
            'Åland Islands',
            'Azores',
            'Canary Islands',
            'Faroe Islands',
            'Gibraltar',
            'Guernsey',
            'Isle of Man',
            'Jan Mayen',
            'Jersey',
            'Madeira',
            'Svalbard',
            'Palma',
            'Ibiza',
            'Corsica',
            'Sardinia',
            'Sicily',
            'Malta',
            'Crete',
            'Cyprus',
            'Santorini',
            'Mykonos',
            'Rhodes',
            'Corfu',
            'Capri',
        ]
    },
    {
        groupName: 'Aisia',
        countries: [
            'Armenia',
            'Bahrain',
            'Bangladesh',
            'Brunei',
            'Cambodia',
            'China',
            'Cyprus',
            'Georgia',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Israel',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kuwait',
            'Kyrgyzstan',
            'Lebanon',
            'Malaysia',
            'Maldives',
            'North Korea',
            'Oman',
            'Palestine',
            'Philippines',
            'Qatar',
            'Saudi Arabia',
            'Singapore',
            'South Korea',
            'Sri Lanka',
            'Syria',
            'Taiwan',
            'Thailand',
            'Timor - Leste',
            'Turkey',
            'United Arab Emirates',
            'Vietnam',
            'Andaman Islands',
            'Nicobar Islands',
            'Hainan Island',
            'Sumatra',
            'Java',
            'Borneo',
            'Sulawesi',
            'Bali',
            'Luzon',
            'Mindanao',
            'Hokkaido',
            'Honshu',
            'Kyushu',
            'Shikoku',
            'Sri Lanka',
            'Taiwan',
            'Haida Gwaii',
            'Sakhalin',
            'Kuril Islands',
            'Jeju Island',
            'Phuket',
            'Maldives',
            'Socotra',
            'Seychelles',
            'Sriwijaya',
            'Penghu Islands',
            'Okinawa Islands',
        ]
    },
    {
        groupName: 'North America',
        countries: [
            'Canada',
            'United States',
            'Mexico',
            'Antigua and Barbuda',
            'Bahamas',
            'Barbados',
            'Belize',
            'Cuba',
            'Dominica',
            'Dominican Republic',
            'Grenada',
            'Haiti',
            'Jamaica',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Vincent and the Grenadines',
            'Trinidad and Tobago',
            'Anguilla',
            'Aruba',
            'Bermuda',
            'Bonaire',
            'British Virgin Islands',
            'Cayman Islands',
            'Curaçao',
            'Greenland',
            'Guadeloupe',
            'Martinique',
            'Montserrat',
            'Navassa Island',
            'Puerto Rico',
            'Saint Martin',
            'Sint Maarten',
            'Turks and Caicos Islands',
            'U.S. Virgin Islands',
            'Vancouver Island',
            'Vancouver',
            'Newfoundland and Labrador',
            'Hispaniola (shared by Haiti and the Dominican Republic)',
            'Cuba',
            'Jamaica',
            'Cozumel',
            'Isla Mujeres',
            'Isla Holbox',
            'Isla Contoy',
            'Isla Mujeres',
            'Isla Holbox',
            'Isla Contoy',
        ]
    },
    {
        groupName: 'South America',
        countries: [
            'Argentina',
            'Bolivia',
            'Brazil',
            'Chile',
            'Costa Rica',
            'Colombia',
            'Ecuador',
            'Guyana',
            'Honduras',
            'Nicaragua',
            'Paraguay',
            'Panama',
            'Peru',
            'Suriname',
            'El Salvdor',
            'Uruguay',
            'Venezuela',
            'French Guiana',
            'Falkland Islands',
            'South Georgia and the South Sandwich Islands',
            'Galápagos Islands',
            'Juan Fernández Islands',
            'Chiloé Archipelago',
            'Tierra del Fuego',
            'Ilhabela',
            'Fernando de Noronha',
            'Ilha Grande',
            'Ilha de Marajó',
            'Margarita Island',
            'Ilha do Mel',
            'Easter Island',
        ]
    },
    {
        groupName: 'Africa',
        countries: [
            'Algeria',
            'Angola',
            'Botswana',
            'Cabo Verde',
            'Cameroon',
            'Congo',
            'Egypt',
            'Equatorial Guinea',
            'Gabon',
            'Ghana',
            "Ivory Coast (Côte d'Ivoire)",
            'Kenya',
            'Libya',
            'Madagascar',
            'Malawi',
            'Mauritius',
            'Morocco',
            'Mozambique',
            'Namibia',
            'Nigeria',
            'Senegal',
            'Seychelles',
            'Sierra Leone',
            'Somalia',
            'South Africa',
            'Tanzania',
            'Tunisia',
            'Canary Islands',
            'Ceuta and Melilla',
            'Madeira',
            'Mayotte',
            'Saint Helena, Ascension, and Tristan da Cunha',
            'Cape Verde Islands',
            'Zanzibar',
            'Socotra',
            'Madagascar',
            'Seychelles Islands',
            'Comoros Islands',
            'Canary Islands',
            'Madeira',
            'São Tomé and Príncipe Islands',
            'Mauritius',
            'Reunion Island',
            'Ascension Island',
            'Tristan da Cunha',
            'Solomon Island',
        ]
    },
    {
        groupName: 'Antarctica',
        countries: [
            'Antarctica',
            'King George Island',
            'Deception Island',
            'Livingston Island',
            'Macquarie Island',
            'Heard Island and McDonald Islands'
        ]
    },
    {
        groupName: 'Australia',
        countries: [
            'Australia',
            'New Zealand',
            'Ashmore and Cartier Islands',
            'Australian Antarctic Territory',
            'Christmas Island',
            'Cocos (Keeling) Islands',
            'Coral Sea Islands',
            'Heard Island and McDonald Islands',
            'Norfolk Island',
            'French Polynesia',
            'Marshall Islands',
            'Niue',
            'Samoa',
            'New Caledonia',
            'Fiji',
            'Tasmania',
            'Kangaroo Island',
            'Fraser Island',
            'Groote Eylandt',
            'Rottnest Island',
            'Lord Howe Island',
            'Norfolk Island',
            'Tiwi Islands',
            'Whitsunday Islands',
            'Magnetic Island',
            'Phillip Island',
            'Hamilton Island',
            'Hayman Island',
            'Flinders Island',
            'Thursday Island',
            'South Stradbroke Island',
            'Moreton Island',
            'Papua New Guinea',
        ]
    }
]